### ISSUE TITLE
No core dump will be written. Minidumps are not enabled by default on client versions of Windows

### ISSUE THREAD

**Issue by mayl0415** [bonede/tree-sitter-ng#47]
Hello,

I'm encountering an issue while running IntelliJ IDEA on Windows 7. The error message I'm seeing is:
No core dump will be written. Minidumps are not enabled by default on client versions of Windows.
......
Current thread (0x000000010099f810):  JavaThread "OkHttp http://10.217.128.15/..." [_thread_in_native, id=9920, stack(0x0000000075a30000,0x0000000075b30000)]

Stack: [0x0000000075a30000,0x0000000075b30000],  sp=0x0000000075b2d850,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x000007feede16475

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 158968  org.treesitter.TSParser.ts_parser_parse_string_encoding(JJLjava/lang/String;I)J (0 bytes) @ 0x000000002d54478a [0x000000002d544720+0x000000000000006a]
J 158967 c1 org.treesitter.TSParser.parseStringEncoding(Lorg/treesitter/TSTree;Ljava/lang/String;Lorg/treesitter/TSInputEncoding;)Lorg/treesitter/TSTree; (40 bytes) @ 0x000000000f902ddc [0x000000000f902cc0+0x000000000000011c]

Environment:
Operating System: Windows 7
IDE Version: IntelliJ IDEA running on JBR-17
CPU: Intel Xeon Gold 5218

**Comment by mayl0415** [comment]
--------------  T H R E A D  ---------------

Current thread (0x000000010099f810):  JavaThread "OkHttp http://10.217.128.15/..." [_thread_in_native, id=9920, stack(0x0000000075a30000,0x0000000075b30000)]

Stack: [0x0000000075a30000,0x0000000075b30000],  sp=0x0000000075b2d850,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x000007feede16475

Java frames:
J 158968  org.treesitter.TSParser.ts_parser_parse_string_encoding(JJLjava/lang/String;I)J (0 bytes) @ 0x000000002d54478a [0x000000002d544720+0x000000000000006a]
...
siginfo: EXCEPTION_ILLEGAL_INSTRUCTION (0xc000001d)
Steps to Reproduce:
Running IntelliJ IDEA with Tree-sitter integration.
The issue occurs when calling the TSParser.ts_parser_parse_string_encoding method.


What could be causing this EXCEPTION_ILLEGAL_INSTRUCTION error?
Is there any configuration or setup that needs to be adjusted to make this work in my environment?
Could this be related to my CPU or the version of Tree-sitter?
Thank you for your help!

**Comment by bonede** [comment]
Please paste the parser you were using and the sample source code to parse.

**Comment by mayl0415** [comment]
Hello, thank you for your reply. I have defined a utility class.
public class TreeSitterClient {

    private final TSParser tsParser;

    /**
     * 手动创建一个新的实例
     * @param tsLanguage
     * @return
     */
    public static  TreeSitterClient createNewInstance(TSLanguage tsLanguage){
        return new TreeSitterClient(tsLanguage);
    }


    TreeSitterClient(TSLanguage tsLanguage) {
        tsParser = new TSParser();
        if (!tsParser.setLanguage(tsLanguage)) {
            throw new RuntimeException("language is not supported");
        }
    }
 public Node getFirstChildNodeByTypes(Node parentNode, String... targetTypes) {
        int n = parentNode.getChildCount();
        for (int i = 0; i < n; i++) {
            Node node = parentNode.getChild(i);
            if (TsNodeUtil.containNodeType(node, targetTypes)) {
                return node;
            }
        }
        return null;
    }
public TSTree getTree(String source) {
        return tsParser.parseString(null, source);
    }

    public TSNode getNode(String source) {
        return tsParser.parseString(null, source).getRootNode();
    }
}

**Comment by bonede** [comment]
Could you paste the source you are parsing?

**Comment by mayl0415** [comment]
I have encountered this problem again, it may be this 
[error.txt](https://github.com/user-attachments/files/17585726/error.txt)

**Comment by HendyLiang27** [comment]
I am not sure whether or not my issue is related to this, but I am getting errors when using JUnit in Eclipse to test the code, but the debugger works just fine. I have three cases (in C++) where I am trying to pattern match:

Code 1:
```cpp
int x = 5;
``` 
Pattern 1:
```cpp
int x = 5;
``` 
First case works just fine in as a J-Unit test. 

Code 2:
```cpp
void main() {
     int x = 5;
}
``` 
Pattern 2:
```cpp
int x = 5;
``` 
Second case gives EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff8e3d56148, pid=66912, tid=16576. 

Code 3:
```cpp
int x = 5;
``` 
Pattern 3:
```cpp
int $VARIABLE = 5;
``` 
Third case gives EXCEPTION_ILLEGAL_INSTRUCTION (0xc000001d) at pc=0x00007ff8e3d56112, pid=36460, tid=47032.

When using the debugger, it doesn't throw these errors. Might it be connected to J-Unit trying to access some of the native methods in TS-NG without permission? Otherwise I would have no clue where this error would come from given the unique circumstances.

**Comment by bonede** [comment]
Hi,

Please upgrade to the latest version of tree sitter and parsers. This should fix the issue.

**Comment by HendyLiang27** [comment]
The error still persists after upgrading.

I suspect that this might be due to multithreading. Our system uses multithreading and I think that there might be attempts to access memory locations that haven't yet been filled/allocated. Does this help?

The error looks like:

# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffffde52f2d, pid=37364, tid=19076
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.12+7 (17.0.12+7) (build 17.0.12+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.12+7 (17.0.12+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [x86_64-windows-tree-sitter.dll+0x2f2d]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# [FILE_LOCATION]
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

**Comment by bonede** [comment]
Could you paste the sample Java code and the C++ source code?

**Comment by HendyLiang27** [comment]
The C++ source code is in the earlier comment. It is hard to provide sample Java code because I am not doing anything other than calling the parser with the correct language. Storing the reference to the node somewhere and accessing the node contents through the native code whenever necessary. Our system is rather large so not all the tree-sitter interactions happen in one file. When I put all the interactions in one file, there is no problem. I think the issue might lie in the use of multithreading where a thread might try to access a piece of memory that is blocked by another thread. This suspicion is because of the fact that JUnit tests cause errors but debug mode doesn't. Does this help?
